spring:
  application:
    name: platform-system-provider
  profiles:
    active: local

mybatis:
  typeAliasesPackage: com.yxhl.stationbiz.system.domain
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/*.xml