spring:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    #password:
    timeout: 0
    pool:
      max-active: 300
      max-idle: 100
      max-wait: -1
      min-idle: 0
      
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: admin
#    password: admin123
#    virtualHost: /

server:
  port: 8187
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: X-Forwarded-Port
    accesslog:
      debug: true #请求响应数据调试
  use-forward-headers: true
  
DUBBO_ZK_URL: zookeeper://127.0.0.1:2181

#oss 配置
aliyun: 
  oss: 
    endpoint: http://oss-cn-shenzhen.aliyuncs.com
    osswebsite: http://tsyly.oss-cn-shenzhen.aliyuncs.com/
    accessKeyId: LTAI74qNL5iRxwsC
    accessKeySecret: JSchOF3kQ68tFEFr4Bb9XnpSduYzzQ
    bucketName: tsyly
    testBucket: tsyly